#!/usr/bin/env bash
# install ngnix

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '0,/listen.*/s/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sudo echo "Holberton School" > /usr/share/nginx/html/index.html
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
