#!/usr/bin/env bash
# configures the nginx server with a custom HTTP header
sudo apt-get -y update
sudo apt-get -y install nginx
host=$(cat /etc/hostname)
sudo sed -i "36 i\ \tadd_header X-Served-By $host;\n" /etc/nginx/sites-enabled/default
sudo service nginx restart
